# Generated by Django 3.2.8 on 2021-10-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='メールアドレス')),
                ('last_name', models.CharField(max_length=100, verbose_name='姓')),
                ('first_name', models.CharField(max_length=100, verbose_name='名')),
                ('last_kana', models.CharField(max_length=100, verbose_name='姓(カナ)')),
                ('first_kana', models.CharField(max_length=100, verbose_name='名(カナ)')),
                ('zip_code', models.CharField(max_length=100, verbose_name='郵便番号')),
                ('prefecture', models.CharField(choices=[('hokkaido', '北海道'), ('aomori', '青森県'), ('iwate', '岩手県'), ('miyagi', '宮城県'), ('akita', '秋田県'), ('yamagata', '山形県'), ('fukushima', '福島県'), ('ibaraki', '茨城県'), ('tochigi', '栃木県'), ('gunma', '群馬県'), ('saitama', '埼玉県'), ('chiba', '千葉県'), ('tokyo', '東京都'), ('kanagawa', '神奈川県'), ('niigata', '新潟県'), ('toyama', '富山県'), ('ishikawa', '石川県'), ('fukui', '福井県'), ('yamanashi', '山梨県'), ('nagano', '長野県'), ('gifu', '岐阜県'), ('shizuoka', '静岡県'), ('aichi', '愛知県'), ('mie', '三重県'), ('shiga', '滋賀県'), ('kyoto', '京都府'), ('osaka', '大阪府'), ('hyogo', '兵庫県'), ('nara', '奈良県'), ('wakayama', '和歌山県'), ('tottori', '鳥取県'), ('shimane', '島根県'), ('okayama', '岡山県'), ('hiroshima', '広島県'), ('yamaguchi', '山口県'), ('tokushima', '徳島県'), ('kagawa', '香川県'), ('ehime', '愛媛県'), ('kochi', '高知県'), ('fukuoka', '福岡県'), ('saga', '佐賀県'), ('nagasaki', '長崎県'), ('kumamoto', '熊本県'), ('oita', '大分県'), ('miyazaki', '宮崎県'), ('kagoshima', '鹿児島県'), ('okinawa', '沖縄県'), ('kaigai', '海外その他')], max_length=100, verbose_name='都道府県')),
                ('city_name', models.CharField(max_length=100, verbose_name='市町村')),
                ('street_name', models.CharField(max_length=100, verbose_name='丁目・番地')),
                ('building_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='建物名')),
                ('tel', models.CharField(max_length=100, verbose_name='電話番号')),
                ('date_of_birth', models.DateTimeField(blank=True, null=True, verbose_name='生年月日')),
                ('gender', models.CharField(blank=True, choices=[('male', '男性'), ('female', '女性'), ('not_applicable', '無回答')], max_length=50, null=True, verbose_name='性別')),
                ('personal_image', models.ImageField(upload_to='media/account')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
