# Generated by Django 3.2.8 on 2021-10-30 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_myuser_personal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='personal_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像'),
        ),
    ]
