# Generated by Django 3.2.8 on 2021-11-09 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Closet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('closet_name', models.CharField(max_length=255, verbose_name='クローゼット名')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'ordering': ['closet_name'],
            },
        ),
        migrations.CreateModel(
            name='PurchasePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('purchase_place', models.CharField(max_length=255, verbose_name='購入場所')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('item_type', models.CharField(max_length=255, verbose_name='アイテム種類')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
        migrations.CreateModel(
            name='ItemColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('item_color', models.CharField(max_length=255, verbose_name='アイテムカラー')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
        migrations.CreateModel(
            name='ItemBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('item_brand', models.CharField(max_length=255, verbose_name='ブランド')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('spring', '春'), ('summer', '夏'), ('fall', '秋'), ('winter', '冬')], max_length=10, verbose_name='季節')),
                ('occasion', models.CharField(choices=[('daily_use', '普段着'), ('work_wear', '仕事'), ('active_wear', 'よそ行き'), ('sports_wear', 'スポーツ'), ('other_use', 'その他')], max_length=30, verbose_name='シーン')),
                ('item_name', models.CharField(max_length=300, verbose_name='アイテム名称')),
                ('purchase_date', models.DateTimeField(blank=True, null=True, verbose_name='購入日')),
                ('pricing', models.IntegerField(verbose_name='購入価格(円)')),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='contens/item_images', verbose_name='アイテム画像')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='メモ')),
                ('favorite_level', models.IntegerField(blank=True, choices=[(1, 'めちゃ低い'), (2, '低い'), (3, '普通'), (4, '高い'), (5, 'めちゃ高い')], null=True, verbose_name='お気に入り度')),
                ('item_importance', models.IntegerField(blank=True, choices=[(1, '捨てれる'), (2, '悩む'), (3, '普通'), (4, 'まあ大事'), (5, 'めっちゃ大事')], null=True, verbose_name='大事さ')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('closet', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='contents.closet')),
                ('item_brand', models.ForeignKey(default=None, max_length=150, on_delete=django.db.models.deletion.PROTECT, to='contents.itembrand', verbose_name='ブランド')),
                ('item_color', models.ForeignKey(default=None, max_length=20, on_delete=django.db.models.deletion.PROTECT, to='contents.itemcolor', verbose_name='アイテム色')),
                ('item_type', models.ForeignKey(default=None, max_length=255, on_delete=django.db.models.deletion.PROTECT, to='contents.itemtype', verbose_name='アイテム種類')),
                ('purchase_place', models.ForeignKey(default=None, max_length=255, on_delete=django.db.models.deletion.PROTECT, to='contents.purchaseplace', verbose_name='購入場所')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'ordering': ['item_name'],
            },
        ),
    ]
