# Generated by Django 3.2.8 on 2021-11-09 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='closet',
        ),
        migrations.AddField(
            model_name='item',
            name='closet_name',
            field=models.ForeignKey(default=None, max_length=255, on_delete=django.db.models.deletion.PROTECT, to='contents.closet', verbose_name='クローゼット名'),
        ),
    ]
