# Generated by Django 3.2.8 on 2021-11-02 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_auto_20211102_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_brand',
            field=models.ForeignKey(blank=True, db_column='item_brand', null=True, on_delete=django.db.models.deletion.CASCADE, to='contents.itembrand', verbose_name='ブランド名称'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_color',
            field=models.ForeignKey(blank=True, db_column='item_color', null=True, on_delete=django.db.models.deletion.CASCADE, to='contents.itemcolor', verbose_name='アイテムカラー'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.ForeignKey(blank=True, db_column='item_type', null=True, on_delete=django.db.models.deletion.CASCADE, to='contents.itemtype', verbose_name='アイテム種類'),
        ),
        migrations.AlterField(
            model_name='item',
            name='purchase_place',
            field=models.ForeignKey(blank=True, db_column='purchase_place', null=True, on_delete=django.db.models.deletion.CASCADE, to='contents.purchaseplace', verbose_name='購入場所'),
        ),
        migrations.AlterField(
            model_name='itemcolor',
            name='item_color',
            field=models.CharField(choices=[('red', '赤'), ('blue', '青'), ('green', '緑'), ('yellow', '黄'), ('purple', '紫'), ('orange', '橙'), ('black', '黒'), ('white', '白'), ('grey', '灰'), ('beige', 'ベージュ'), ('navy', 'ネイビー'), ('brown', '茶'), ('others', 'その他')], max_length=100, unique=True, verbose_name='アイテムカラー'),
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='item_type',
            field=models.CharField(choices=[('jacket', '上着'), ('shirt', 'シャツ'), ('pants', 'パンツ'), ('underpants', '下着(下)'), ('undershirt', '下着(上)'), ('socks', '靴下'), ('others', 'その他')], max_length=155, unique=True, verbose_name='アイテム種類'),
        ),
    ]
