# Generated by Django 3.2.8 on 2021-11-13 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_auto_20211109_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='closet_name',
            field=models.ForeignKey(max_length=255, null=True, on_delete=django.db.models.deletion.PROTECT, to='contents.closet', verbose_name='クローゼット名'),
        ),
        migrations.AlterField(
            model_name='item',
            name='favorite_level',
            field=models.IntegerField(blank=True, choices=[(1, 'めちゃ低い'), (2, '低い'), (3, '普通'), (4, '高い'), (5, 'めちゃ高い')], default=None, null=True, verbose_name='お気に入り度'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_importance',
            field=models.IntegerField(blank=True, choices=[(1, '捨てれる'), (2, '悩む'), (3, '普通'), (4, 'まあ大事'), (5, 'めっちゃ大事')], default=None, null=True, verbose_name='大事さ'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contents.itemtype', verbose_name='アイテム種類'),
        ),
        migrations.AlterField(
            model_name='item',
            name='occasion',
            field=models.CharField(choices=[('daily_use', '普段着'), ('work_wear', '仕事'), ('active_wear', 'よそ行き'), ('sports_wear', 'スポーツ'), ('other_use', 'その他')], default='daily_use', max_length=30, verbose_name='シーン'),
        ),
        migrations.AlterField(
            model_name='item',
            name='season',
            field=models.CharField(choices=[('spring', '春'), ('summer', '夏'), ('fall', '秋'), ('winter', '冬')], default='spring', max_length=10, verbose_name='季節'),
        ),
    ]
