# Generated by Django 3.2.8 on 2021-11-13 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_auto_20211113_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='closet_name',
        ),
        migrations.AddField(
            model_name='item',
            name='closet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contents.closet', verbose_name='クローゼット名'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contents.itembrand', verbose_name='ブランド'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contents.itemcolor', verbose_name='アイテム色'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contents.itemtype', verbose_name='アイテム種類'),
        ),
        migrations.AlterField(
            model_name='item',
            name='purchase_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contents.purchaseplace', verbose_name='購入場所'),
        ),
    ]
