# Generated by Django 3.2.8 on 2021-11-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_auto_20211103_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itembrand',
            name='item_brand',
            field=models.CharField(max_length=155, verbose_name='ブランド'),
        ),
        migrations.AlterField(
            model_name='itemcolor',
            name='item_color',
            field=models.CharField(max_length=100, verbose_name='アイテムカラー'),
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='item_type',
            field=models.CharField(max_length=155, verbose_name='アイテム種類'),
        ),
        migrations.AlterField(
            model_name='purchaseplace',
            name='purchase_place',
            field=models.CharField(max_length=155, verbose_name='購入場所'),
        ),
    ]
