# Generated by Django 3.2.8 on 2021-11-04 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0005_auto_20211103_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_brand',
            field=models.ForeignKey(blank=True, db_column='item_brand', default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='contents.itembrand', verbose_name='ブランド名称'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_color',
            field=models.ForeignKey(blank=True, db_column='item_color', default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='contents.itemcolor', verbose_name='アイテムカラー'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.ForeignKey(blank=True, db_column='item_type', default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='contents.itemtype', verbose_name='アイテム種類'),
        ),
        migrations.AlterField(
            model_name='item',
            name='purchase_place',
            field=models.ForeignKey(blank=True, db_column='purchase_place', default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='contents.purchaseplace', verbose_name='購入場所'),
        ),
    ]
