# Generated by Django 3.2.8 on 2021-11-25 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0005_auto_20211113_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closet',
            name='closet_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='クローゼット名'),
        ),
        migrations.AlterField(
            model_name='item',
            name='closet',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='contents.closet'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_brand',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contents.itembrand'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_color',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contents.itemcolor'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=300, unique=True, verbose_name='アイテム名称'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contents.itemtype'),
        ),
        migrations.AlterField(
            model_name='item',
            name='purchase_place',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contents.purchaseplace'),
        ),
        migrations.AlterField(
            model_name='itembrand',
            name='item_brand',
            field=models.CharField(max_length=255, unique=True, verbose_name='ブランド'),
        ),
        migrations.AlterField(
            model_name='itemcolor',
            name='item_color',
            field=models.CharField(max_length=255, unique=True, verbose_name='アイテムカラー'),
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='item_type',
            field=models.CharField(max_length=255, unique=True, verbose_name='アイテム種類'),
        ),
        migrations.AlterField(
            model_name='purchaseplace',
            name='purchase_place',
            field=models.CharField(max_length=255, unique=True, verbose_name='購入場所'),
        ),
    ]
