# Generated by Django 3.2.8 on 2021-11-28 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0006_auto_20211125_2147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['create_date']},
        ),
    ]
