# Generated by Django 3.2.8 on 2021-11-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0006_auto_20211104_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtype',
            name='item_type',
            field=models.CharField(choices=[('jacket', '上着'), ('shirt', 'シャツ'), ('pants', 'パンツ'), ('underpants', '下着(下)'), ('undershirt', '下着(上)'), ('socks', '靴下'), ('others', 'その他')], max_length=155, verbose_name='アイテム種類'),
        ),
    ]
