# Generated by Django 3.2.8 on 2021-11-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0007_alter_item_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to='contents/item_images', verbose_name='アイテム画像'),
        ),
    ]
