from django.urls import path

from .views import ( 
    item_type_CreateView, item_type_CreateCompleteView, item_color_CreateView, item_color_CreateCompleteView, item_brand_CreateView, item_brand_CreateCompleteView,
    purchase_place_CreateView, purchase_place_CreateCompleteView, closet_CreateView, closet_CreateCompleteView, item_Createview, item_CreateCompleteView, item_category_GateView,
    item_ListView, item_DetailView, item_DeleteView, item_Delete_CompleteView, item_type_DeleteView, item_type_Delete_CompleteView, item_color_DeleteView, item_color_Delete_CompleteView,
    item_brand_DeleteView, item_brand_Delete_CompleteView, purchase_place_DeleteView, purchase_place_Delete_CompleteView, closet_DeleteView, closet_Delete_CompleteView,
    closet_DeleteView, closet_Delete_CompleteView, item_type_UpdateView, item_type_UpdateCompleteView, item_color_UpdateView, item_color_UpdateCompleteView,
    item_brand_UpdateView, item_brand_UpdateCompleteView, purchase_place_UpdateView, purchase_place_UpdateCompleteView, closet_UpdateView, closet_UpdateCompleteView,
    item_Updateview, item_Update_CompleteView
)

urlpatterns = [
    path('item-category-gate/', item_category_GateView, name='item_category_gate'),
    path('item-type-create/', item_type_CreateView, name='item_type_create'),
    path('item-type-create-complete/', item_type_CreateCompleteView, name='item_type_create_complete'),
    path('item-type-update/<int:pk>/', item_type_UpdateView, name='item_type_update'),
    path('item-type-update-complete/', item_type_UpdateCompleteView, name='item_type_update_complete'),
    path('item-type-delete/<int:pk>/', item_type_DeleteView, name='item_type_delete'),
    path('item-type-delete-complete/', item_type_Delete_CompleteView, name='item_type_delete_complete'),
    path('item-color-create/', item_color_CreateView, name='item_color_create'),
    path('item-color-create-complete/', item_color_CreateCompleteView, name='item_color_create_complete'),
    path('item-color-update/<int:pk>/', item_color_UpdateView, name='item_color_update'),
    path('item-color-update-complete/', item_color_UpdateCompleteView, name='item_color_update_complete'),
    path('item-color-delete/<int:pk>/', item_color_DeleteView, name='item_color_delete'),
    path('item-color-delete-complete/', item_color_Delete_CompleteView, name='item_color_delete_complete'),
    path('item-brand-create/', item_brand_CreateView, name='item_brand_create'),
    path('item-brand-create-complete/', item_brand_CreateCompleteView, name='item_brand_create_complete'),
    path('item-brand-update/<int:pk>/', item_brand_UpdateView, name='item_brand_update'),
    path('item-brand-update-complete/', item_brand_UpdateCompleteView, name='item_brand_update_complete'),
    path('item-brand-delete/<int:pk>/', item_brand_DeleteView, name='item_brand_delete'),
    path('item-brand-delete-complete/', item_brand_Delete_CompleteView, name='item_brand_delete_complete'),
    path('purchase-place-create/', purchase_place_CreateView, name='purchase_place_create'),
    path('purchase-place-create-complete/', purchase_place_CreateCompleteView, name='purchase_place_create_complete'),
    path('purchase-place-update/<int:pk>/', purchase_place_UpdateView, name='purchase_place_update'),
    path('purchase-place-update-complete/', purchase_place_UpdateCompleteView, name='purchase_place_update_complete'),
    path('purchase-place-delete/<int:pk>/', purchase_place_DeleteView, name='purchase_place_delete'),
    path('purchase-place-delete-complete/', purchase_place_Delete_CompleteView, name='purchase_place_delete_complete'),
    path('closet-create/', closet_CreateView, name='closet_create'),
    path('closet-create-complete/', closet_CreateCompleteView, name='closet_create_complete'),
    path('closet-update/<int:pk>/', closet_UpdateView, name='closet_update'),
    path('closet-update-complete/', closet_UpdateCompleteView, name='closet_update_complete'),
    path('closet-delete/<int:pk>/', closet_DeleteView, name='closet_delete'),
    path('closet-delete-complete/', closet_Delete_CompleteView, name='closet_delete_complete'),
    path('item-create/', item_Createview, name='item_create'),
    path('item-create-complete/', item_CreateCompleteView, name='item_create_complete'),
    path('item-update/<int:pk>/', item_Updateview, name='item_update'),
    path('item-update-complete/', item_Update_CompleteView, name='item_update_complete'),
    path('item-list/', item_ListView, name='item_list'),
    path('item-detail/<int:pk>/', item_DetailView, name='item_detail'),
    path('item-delete/<int:pk>/', item_DeleteView, name='item_delete'),
    path('item-delete-complete/', item_Delete_CompleteView, name='item_delete_complete'),
]